# Generated by Django 5.2.4 on 2025-08-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
        ('payments', '0002_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votetransaction',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='votetransaction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votetransaction',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votetransaction',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votetransaction',
            name='provider',
            field=models.CharField(choices=[('mtn', 'MTN'), ('airtel', 'Airtel'), ('telecel', 'Telecel')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votetransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
