# Generated by Django 5.2.4 on 2025-08-21 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_amount_paid_votetransaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votetransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='votetransaction',
            name='event',
        ),
        migrations.AlterField(
            model_name='votetransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='votetransaction',
            name='payment_reference',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
