# Generated by Django 5.2.4 on 2025-08-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_otp'),
        ('payments', '0005_withdrawaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawaltransaction',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawaltransaction',
            name='otp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.otp'),
            preserve_default=False,
        ),
    ]
