# Generated by Django 5.2.4 on 2025-08-26 09:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_withdrawaltransaction_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank')], max_length=10)),
                ('provider', models.CharField(choices=[('mtn', 'MTN'), ('airtel', 'Airtel'), ('telecel', 'Telecel')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('external_payment_id', models.CharField(max_length=100, null=True, unique=True)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('transfer', 'Transfer')], max_length=20)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
