# Generated by Django 5.2.4 on 2025-08-26 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_method',
            new_name='channel',
        ),
    ]
