# Generated by Django 5.2.4 on 2025-08-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_rename_payment_method_transaction_channel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteTransaction',
        ),
    ]
