# Generated by Django 5.2.4 on 2025-08-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_delete_votetransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WithdrawalTransaction',
        ),
    ]
