# Generated by Django 5.2.4 on 2025-09-09 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_delete_withdrawaltransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhooklog',
            old_name='candidate_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='webhooklog',
            old_name='event_id',
            new_name='instance_id',
        ),
        migrations.RemoveField(
            model_name='webhooklog',
            name='received_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='product',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
