# Generated by Django 5.2.4 on 2025-08-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='achivements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
    ]
