# Generated by Django 5.2.4 on 2025-08-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ticket_ticketsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
