# Generated by Django 5.2.4 on 2025-08-27 00:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ticketsale_recipient_email'),
        ('payments', '0009_delete_votetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteTransaction',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_count', models.PositiveIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
