# Generated by Django 5.2.4 on 2025-08-28 16:43

import core.models.otp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_withdrawaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='prefix',
            field=models.CharField(default=core.models.otp.generate_prefix, max_length=6),
        ),
    ]
