# Generated by Django 5.2.4 on 2025-08-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfer_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='transfer_limit',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
