# Generated by Django 5.2.4 on 2025-08-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_transfer_allowed_user_transfer_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.otp'),
        ),
    ]
