# Generated by Django 5.2.4 on 2025-09-13 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
