# Generated by Django 5.2.4 on 2025-09-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ticketsale_created_at_ticketsale_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsale',
            old_name='customer_name',
            new_name='recipient_name',
        ),
    ]
